--
-- PostgreSQL database dump
--

\restrict bRgawNwspddF2S5wvrcGW2mOK7c9YAQMzIAzKVtwEA2z0pgctlVhXQxfevZ3gBs

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: despesa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.despesa (
    id bigint NOT NULL,
    categoria character varying(50) NOT NULL,
    data date NOT NULL,
    descricao character varying(200) NOT NULL,
    observacoes character varying(500),
    recorrente boolean NOT NULL,
    valor numeric(10,2) NOT NULL,
    user_id bigint
);


ALTER TABLE public.despesa OWNER TO postgres;

--
-- Name: despesa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.despesa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.despesa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entrada_estoque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.entrada_estoque (
    id bigint NOT NULL,
    custo_total numeric(10,2) NOT NULL,
    custo_unitario numeric(10,2) NOT NULL,
    data_entrada timestamp(6) without time zone NOT NULL,
    quantidade integer NOT NULL,
    saldo integer NOT NULL,
    produto_id bigint NOT NULL,
    categoria character varying(255),
    fornecedor character varying(255),
    id_pedido_compra character varying(255),
    observacoes character varying(1000),
    user_id bigint
);


ALTER TABLE public.entrada_estoque OWNER TO postgres;

--
-- Name: entrada_estoque_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.entrada_estoque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entrada_estoque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_venda; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item_venda (
    id bigint NOT NULL,
    custo_unitario numeric(10,2) NOT NULL,
    quantidade integer NOT NULL,
    lote_id bigint NOT NULL,
    venda_id bigint NOT NULL,
    user_id bigint
);


ALTER TABLE public.item_venda OWNER TO postgres;

--
-- Name: item_venda_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item_venda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_venda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produto (
    id bigint NOT NULL,
    sku character varying(255) NOT NULL,
    asin character varying(255),
    nome character varying(255) NOT NULL,
    descricao character varying(255),
    data_criacao timestamp without time zone NOT NULL,
    quantidade_estoque integer DEFAULT 0 NOT NULL,
    estoque_minimo integer DEFAULT 5 NOT NULL,
    user_id bigint
);


ALTER TABLE public.produto OWNER TO postgres;

--
-- Name: produto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.produto_id_seq OWNER TO postgres;

--
-- Name: produto_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.produto_id_seq OWNED BY public.produto.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    data_criacao timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: venda; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venda (
    id bigint NOT NULL,
    custo_envio double precision NOT NULL,
    custo_produto_vendido double precision NOT NULL,
    data timestamp(6) without time zone NOT NULL,
    frete_pago_pelo_cliente double precision NOT NULL,
    id_pedido character varying(255) NOT NULL,
    plataforma character varying(255) NOT NULL,
    preco_venda double precision NOT NULL,
    quantidade integer NOT NULL,
    tarifa_plataforma double precision NOT NULL,
    produto_id bigint NOT NULL,
    despesas_operacionais double precision DEFAULT 0.0,
    user_id bigint,
    data_venda timestamp(6) without time zone,
    frete_pago_cliente double precision
);


ALTER TABLE public.venda OWNER TO postgres;

--
-- Name: venda_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.venda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produto id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto ALTER COLUMN id SET DEFAULT nextval('public.produto_id_seq'::regclass);


--
-- Data for Name: despesa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.despesa (id, categoria, data, descricao, observacoes, recorrente, valor, user_id) FROM stdin;
4	Outros	2025-11-01	Despesa teste		f	100.00	1
5	Embalagem	2025-11-05	Envelope de segurança kit com 5 unidades - 40x50		f	4.75	5
6	Embalagem	2025-11-05	Envelope de segurança kit com 10 unidades - 26x36	Dois pacotes de 5 unidades a R$ 4,40 cada	f	8.81	5
7	Material de Escritório	2025-11-06	 Produto Imagem do produto Pacote de Papel A4 para impressão – 500 Folhas por Pacote 70g		f	23.40	5
8	Material de Escritório	2025-11-08	Cartucho HP 667XL Preto Para Impressoras Deskjet Ink Advantage		f	79.21	5
\.


--
-- Data for Name: entrada_estoque; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.entrada_estoque (id, custo_total, custo_unitario, data_entrada, quantidade, saldo, produto_id, categoria, fornecedor, id_pedido_compra, observacoes, user_id) FROM stdin;
70	23.36	23.36	2025-11-06 16:35:28.57918	1	0	27	Produto	LumiCasa - Shopee	251011RC7FUKQV		5
69	70.35	23.45	2025-11-06 08:15:20.818754	3	0	25	Produto	Shop1104020073 Store - AliExpress	8205401891473147-0	Compra de 9 unidades a R$ 211,05	5
71	75.34	37.67	2025-11-06 17:17:32.57595	2	0	28	Produto	HJMY2B0.br - Shopee	2508088FUPYSEX		5
43	32.90	16.45	2025-10-23 15:07:59.134485	2	0	15	Produto	Shop1104020073 Store	8205153891933147		1
57	46.90	23.45	2025-11-03 16:02:08.311395	2	2	21	Produto	Fornecedor ABC	1234567		2
44	211.05	23.45	2025-10-23 17:59:40.286251	9	4	15	Produto	Shop1104020073 Store	8205401891473147		1
72	10.60	3.53	2025-11-06 17:33:55.42938	3	2	29	Produto	estrela237 - Sopee	251011RCBEQFDT		5
58	117.25	23.45	2025-11-03 16:06:02.178176	5	4	22	Produto	Fornecedor ABC	123456789		1
63	10.00	10.00	2025-11-05 17:34:46.442671	1	1	22	Produto	Fornecedor ABC	COMPRA001		1
64	10.00	10.00	2025-11-05 17:44:33.740661	1	1	22	Produto	Fornecedor A	1234		1
65	70.35	23.45	2025-11-05 17:45:47.504846	3	3	22	Produto	Shop1104020073 Store - AliExpress	128283737774		1
66	70.35	23.45	2025-11-05 17:48:05.665075	3	3	26	Produto	Shop1104020073 Store - AliExpress	8205401891473147-user1	Compra de 9 unidades a R$ 211,05	1
74	17.95	17.95	2025-11-06 18:17:38.561635	1	0	31	Produto	ATLAS.BR - Shopee	2511063NFH7X5B		5
73	209.38	104.69	2025-11-06 17:44:10.555953	2	0	30	Produto	OP Comercio - Shopee	251030F1XJS6M2		5
75	26.59	8.86	2025-11-06 18:48:27.082992	3	0	32	Produto	Ebuy Store - Shopee	251030F1XJS6M3		5
76	88.35	29.45	2025-11-07 17:29:39.546845	3	2	33	Produto	Erc Imports - Shopee	25110764URJN17		5
77	22.56	22.56	2025-11-07 17:36:05.324683	1	0	27	Produto	DMD COMPANY - Shopee	251104TKPHTRTU		5
78	70.31	70.31	2025-11-10 16:12:07.64909	1	0	34	Produto	BPX-STORE - Shopee	251011RC7FUKQT		5
\.


--
-- Data for Name: item_venda; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.item_venda (id, custo_unitario, quantidade, lote_id, venda_id, user_id) FROM stdin;
10	23.45	1	58	54	1
11	23.45	1	69	55	5
12	23.45	1	69	56	5
14	23.36	1	70	58	5
15	23.45	1	69	59	5
16	37.67	2	71	60	5
17	3.53	1	72	61	5
18	104.69	1	73	62	5
19	17.95	1	74	63	5
20	104.69	1	73	64	5
21	8.86	3	75	65	5
22	29.45	1	76	66	5
23	22.56	1	77	67	5
24	70.31	1	78	68	5
\.


--
-- Data for Name: produto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.produto (id, sku, asin, nome, descricao, data_criacao, quantidade_estoque, estoque_minimo, user_id) FROM stdin;
21	2H-0GAU-V9JF	B0F43X4YPZ	Espanta Cachorro Repelente Ultrassônico Eletrônico Portatil		2025-11-03 18:57:22.578	0	5	2
22	12345	123456	Teste Produto estoque	testes para estoque	2025-11-03 19:05:12.152	0	5	1
25	PET-CES-ULT-LED-01	B0887WZ129	Treinador Ultrassônico Antilatidos para Cães com LED	Dispositivo ultrassônico para adestramento canino que emite sons de alta frequência e luz LED para controlar latidos excessivos de cães de forma segura e eficiente.	2025-11-05 20:16:19.093	0	9	5
26	PET-CES-ULT-001	B0887WZ129	Treinador Ultrassônico Antilatidos para Cães com LED	Dispositivo ultrassônico para adestramento canino que emite sons de alta frequência e luz LED para controlar latidos excessivos de cães de forma segura e eficiente.	2025-11-05 20:38:35.316	0	9	1
15	V3-QI16-1FRX	B0887WZ129	Dispositivo de controle ultrassônico antilatido de cães 	Repelente ultrassônico para cães da Alfaw, anti-latido eletrônico, anti-latido, portátil 3 em 1, treinador de cães com lanterna LED, dispositivo de treinamento para cães para sua segurança – ferramenta de prevenção de cães/parar latidos	2025-10-23 18:04:50.339	0	0	1
28	FER-DEC-CABO-01	B0CWYD5PM8	Alicate Descascador e Cortador de Fios Professional	Alicate profissional duplo para descascar e cortar fios elétricos com precisão, lâmina afiada e regulagem para diferentes espessuras.	2025-11-06 20:06:15.054	0	0	5
27	CZS-DES-VASO-01	B0CWCRX8S5	Desentupidor de Vaso Sanitário Profissional de Alta Pressão	Desentupidor profissional para vasos sanitários com sistema de alta pressão, vedação perfeita e durabilidade garantida para desobstrução eficiente.	2025-11-06 19:31:13.029	0	0	5
29	CZS-ABR-LATA-01	B0CCS1K28K	Abridor de Frascos e Potes Sob Armário Multifuncional 	Abridor de frascos com instalação sob armário - auxilia idosos e pessoas com artrite a abrir tampas de qualquer tamanho sem esforço, através de mecanismo resistente e alavanca facilitada.	2025-11-06 20:26:34.769	0	2	5
30	BEM-MAS-CERV-01	B0FM1M1ZJJ	Massageador Cervical Elétrico - Alívio de Dores no Pescoço	Almofada massageadora cervical elétrica com tecnologia de vibração e calor para alívio de dores musculares, tensão no pescoço e promoção de relaxamento profundo.	2025-11-06 20:39:38.022	0	1	5
31	BEM-DEP-TECI-01		Aparelho Portátil Removedor de Bolas de Pelos em Roupas	Aparelho portátil elétrico para remover bolas de pelos e fiapos de roupas, tecidos e estofados, com design compacto e operação simplificada.	2025-11-06 21:13:21.127	0	0	5
32	ACE-SUP-CELU-01	B081B47SJ4	Suporte Celular Anel Dedo 360° Antifurto Queda 3 Em 1	Suporte celular 3 em 1 com anel de dedo giratório 360°, proteção antifurto e sistema antqueda para segurança total do smartphone.	2025-11-06 21:42:27.433	0	2	5
33	BEM-LAM-BARB-01		Refil Lâmina De Reposição Para Barbeador Oneblade	Lâmina OneBlade verde limão para barbear e aparar, proporcionando corte preciso e confortável com tecnologia avançada.	2025-11-07 20:26:32.903	0	0	5
34	BRQ-XAD-MAGN-01	B0FLGDN3H1	Jogo de Xadrez Magnético com Peças Imantadas	Jogo de xadrez magnético com 20 peças esféricas imanadas - promove diversão em família, desenvolve pensamento lógico e estratégico, com design de alta qualidade para horas de entretenimento educativo.	2025-11-10 19:05:41.807	0	0	5
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, ativo, data_criacao, email, nome, password) FROM stdin;
1	t	2025-10-29 09:35:52.951242	admin@multivendas.com	Administrador	$2a$10$tuEXD.eag74uWuhaGp3HJurAKJH3i7LX04lpbV7PQCFAPLUEimZAq
2	t	2025-10-29 09:39:53.074846	teste@multivendas.com	Usuário Teste	$2a$10$bGHce4QxI9eUOknpXI5FkuNodopUBPnEZDIAyWGjv.C56./HUr5SC
3	t	2025-10-29 16:55:54.642534	teste1@gmail.com	Teste Registro	$2a$10$WfwKBj1nMF8ZuPDNVEx5wevkkk7X0wXrXNgbdb830VjAzRhcNa3uq
4	t	2025-10-29 18:19:12.086913	teste2@gmail.com	MultiVendas Teste	$2a$10$L3Psyx.L6IEKoHLvz.Klleyaxz/wLK1MjbBFOQhcB2lg1ueVA84Rm
5	t	2025-11-05 17:02:21.370368	fernandolelis.rocha@gmail.com	Guia Shopping	$2a$10$x4FOdTQZ631205K35byCEeLDtkN1R5ovEtwqvhQ6vk0K/jjI7pVyW
\.


--
-- Data for Name: venda; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.venda (id, custo_envio, custo_produto_vendido, data, frete_pago_pelo_cliente, id_pedido, plataforma, preco_venda, quantidade, tarifa_plataforma, produto_id, despesas_operacionais, user_id, data_venda, frete_pago_cliente) FROM stdin;
55	0	23.45	2025-11-01 11:43:00	0	2000013629757110	Mercado Livre	73.25	1	15.91	25	0	5	\N	\N
56	0	23.45	2025-11-02 11:46:00	0	2000013641255722	Mercado Livre	73.25	1	15.91	25	0	5	\N	\N
58	0	23.36	2025-11-03 19:38:00	0	2000009819530049	Mercado Livre	74.95	1	16.49	27	0	5	\N	\N
59	0	23.45	2025-11-03 20:02:00	0	2000009831289621	Mercado Livre	73.25	1	15.91	25	0	5	\N	\N
60	0	75.34	2025-11-04 20:17:00	0	2000009837300763	Mercado Livre	157.8	2	32.44	28	0	5	\N	\N
61	0	3.53	2025-11-04 20:34:00	0	2000009840457299	Mercado Livre	26.05	1	9.25	29	0	5	\N	\N
62	24.95	104.69	2025-11-04 20:44:00	0	2000009848002353	Mercado Livre	289.9	1	49.28	30	0	5	\N	\N
63	0	17.95	2025-11-06 21:22:00	0	2000009868986113	Mercado Livre	46.49	1	11.61	31	0	5	\N	\N
64	24.95	104.69	2025-11-06 21:24:00	0	2000009874412441	Mercado Livre	289.9	1	49.28	30	0	5	\N	\N
65	0	26.58	2025-11-06 21:49:00	0	2000009880997191	Mercado Livre	89.97	3	31.2	32	0	5	\N	\N
54	0	23.45	2025-11-05 18:38:00	0	233344343434	Mercado Livre	20	1	0	22	0	1	\N	\N
66	0	29.45	2025-11-06 20:32:00	0	2000009886610561	Mercado Livre	59	1	15.01	33	0	5	\N	\N
67	0	22.56	2025-11-07 20:36:00	0	2000009892254483	Mercado Livre	74.95	1	16.49	27	0	5	\N	\N
68	17.96	70.31	2025-11-10 19:12:00	0	2000009934347161	Mercado Livre	143.91	1	23.75	34	0	5	\N	\N
\.


--
-- Name: despesa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.despesa_id_seq', 8, true);


--
-- Name: entrada_estoque_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.entrada_estoque_id_seq', 78, true);


--
-- Name: item_venda_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_venda_id_seq', 24, true);


--
-- Name: produto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produto_id_seq', 34, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- Name: venda_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.venda_id_seq', 68, true);


--
-- Name: despesa despesa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.despesa
    ADD CONSTRAINT despesa_pkey PRIMARY KEY (id);


--
-- Name: entrada_estoque entrada_estoque_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entrada_estoque
    ADD CONSTRAINT entrada_estoque_pkey PRIMARY KEY (id);


--
-- Name: item_venda item_venda_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_venda
    ADD CONSTRAINT item_venda_pkey PRIMARY KEY (id);


--
-- Name: produto produto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_pkey PRIMARY KEY (id);


--
-- Name: produto produto_sku_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_sku_key UNIQUE (sku);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: entrada_estoque uk83sxkf1ab4yfl2rv3kow6t67o; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entrada_estoque
    ADD CONSTRAINT uk83sxkf1ab4yfl2rv3kow6t67o UNIQUE (id_pedido_compra, user_id);


--
-- Name: entrada_estoque ukkgwb1lc58ppknf37w7urfutco; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entrada_estoque
    ADD CONSTRAINT ukkgwb1lc58ppknf37w7urfutco UNIQUE (id_pedido_compra);


--
-- Name: venda ukovn92xocoprrgow7gsnwbbf65; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT ukovn92xocoprrgow7gsnwbbf65 UNIQUE (id_pedido);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: venda venda_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT venda_pkey PRIMARY KEY (id);


--
-- Name: entrada_estoque fk4w9j8s1wbg6y0h4dylouoivk9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entrada_estoque
    ADD CONSTRAINT fk4w9j8s1wbg6y0h4dylouoivk9 FOREIGN KEY (produto_id) REFERENCES public.produto(id);


--
-- Name: despesa fk_despesa_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.despesa
    ADD CONSTRAINT fk_despesa_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: entrada_estoque fk_entrada_estoque_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entrada_estoque
    ADD CONSTRAINT fk_entrada_estoque_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: item_venda fk_item_venda_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_venda
    ADD CONSTRAINT fk_item_venda_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: produto fk_produto_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT fk_produto_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: venda fk_venda_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT fk_venda_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: item_venda fkhg4k9sy7g7a5evecetdbxw294; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_venda
    ADD CONSTRAINT fkhg4k9sy7g7a5evecetdbxw294 FOREIGN KEY (lote_id) REFERENCES public.entrada_estoque(id);


--
-- Name: item_venda fkkiky88fkai72328rhw3r3yebx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_venda
    ADD CONSTRAINT fkkiky88fkai72328rhw3r3yebx FOREIGN KEY (venda_id) REFERENCES public.venda(id);


--
-- Name: venda fkppe4v1vxm9voncsp5d2753yws; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT fkppe4v1vxm9voncsp5d2753yws FOREIGN KEY (produto_id) REFERENCES public.produto(id);


--
-- PostgreSQL database dump complete
--

\unrestrict bRgawNwspddF2S5wvrcGW2mOK7c9YAQMzIAzKVtwEA2z0pgctlVhXQxfevZ3gBs

